// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return web; // reuse web config for Windows desktop
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi4WHFZN4eIzcIfdaOh-0sb0EQPEq84Zg',
    appId: '1:546230757751:web:95b6c9de207483fc3d9972',
    messagingSenderId: '546230757751',
    projectId: 'bodyclone-ai',
    authDomain: 'bodyclone-ai.firebaseapp.com',
    storageBucket: 'bodyclone-ai.firebasestorage.app',
    measurementId: 'G-KPHT9B2R5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx1Il9bTCaTTH9uno_-F5XxVxjyGGY14A',
    appId: '1:546230757751:android:4afb4ff5a1d440c63d9972',
    messagingSenderId: '546230757751',
    projectId: 'bodyclone-ai',
    storageBucket: 'bodyclone-ai.firebasestorage.app',
  );
}
